version: '3.9'

services:
  chromadb:
    container_name: "ChromaDB"
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - /var/chromadb/index-data:/chroma/chroma/
    environment:
      - ALLOW_RESET=True
    ports:
      - 8000:8000
    restart: always

  text_generation_inference:
    container_name: "TGI"
    image: ghcr.io/huggingface/text-generation-inference:latest
    shm_size: 1g
    volumes:
      - /var/ragnarok/TGI/data:/data
    environment:
      - MODEL_ID=TheBloke/zephyr-7B-beta-AWQ
      - MAX_INPUT_LENGTH=3072
      - MAX_TOTAL_TOKENS=4096
      - CUDA_MEMORY_FRACTION=0.8
      - TRUST_REMOTE_CODE=false
      - QUANTIZE=awq
      - SHARDED=false
    ports:
      - 8080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  text_embeddings_inference:
    container_name: "TEI"
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    volumes:
      - /var/ragnarok/TEI/data:/data
    environment:
      - MODEL_ID=BAAI/bge-large-en-v1.5
      - MAX_CLIENT_BATCH_SIZE=128
    ports:
      - 8081:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

volumes:
  backups:
    driver: local
  index-data:
    driver: local
