version: '3.9'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - /var/chromadb/index-data:/chroma/chroma/
    environment:
      - ALLOW_RESET=True
    ports:
      - 8000:8000
    restart: always

  text_generation_inference:
    image: ghcr.io/huggingface/text-generation-inference:latest
    volumes:
      - /stuff/volumes/ragnarok/TGI/data:/data
      - /tmp:/tmp
    environment:
      - MODEL_ID=TheBloke/Mistral-7B-Instruct-v0.1-GPTQ
      - MAX_INPUT_LENGTH=3072
      - MAX_TOTAL_TOKENS=4096
      - CUDA_MEMORY_FRACTION=0.6
      - TRUST_REMOTE_CODE=false
      - QUANTIZE=gptq
      - SHARDED=false
    ports:
      - 8080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    volumes:
      - /stuff/volumes/ragnarok/TEI/data:/data
    command: --model-id thenlper/gte-base
    ports:
      - 8081:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

volumes:
  backups:
    driver: local
  index-data:
    driver: local
