version: '3.9'

networks:
  net:
    driver: bridge

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - /var/chromadb/index-data:/chroma/chroma/
    environment:
      - ALLOW_RESET=True
    ports:
      - 8000:8000
    networks:
      - net
  llama:
    image: thebloke--llama-2-7b-chat-gptq-service:<put_your_tag>
    ports:
      - 3000:3000
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  

volumes:
  backups:
    driver: local
  index-data:
    driver: local
