version: '3.9'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - /var/chromadb/index-data:/chroma/chroma/
    environment:
      - ALLOW_RESET=True
    ports:
      - 8000:8000
    restart: always

  text_generation_inference:
    image: ghcr.io/huggingface/text-generation-inference:latest
    volumes:
      - /var/ragnarok/TGI/data:/data
      - /tmp:/tmp
    environment:
      - MODEL_ID=thebloke/mistrallite-7b-gptq
      - MAX_INPUT_LENGTH=4096
      - MAX_TOTAL_TOKENS=5096
      - CUDA_MEMORY_FRACTION=0.6
      - TRUST_REMOTE_CODE=false
      - QUANTIZE=gptq
      - SHARDED=false
    ports:
      - 8080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    volumes:
      - /var/ragnarok/TEI/data:/data
    command: --model-id BAAI/bge-large-en-v1.5
    ports:
      - 8081:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  backups:
    driver: local
  index-data:
    driver: local
