services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - /var/chromadb/index-data:/chroma/chroma/
    environment:
      - ALLOW_RESET=True
    ports:
      - 8000:8000
    restart: always

  text_generation_inference:
    image: ghcr.io/huggingface/text-generation-inference:latest
    shm_size: 1g
    volumes:
      - /var/ragnarok/TGI/data:/data
    environment:
      - MODEL_ID=mistralai/Mistral-7B-Instruct-v0.2
      - MAX_INPUT_LENGTH=8192
      - MAX_BATCH_PREFILL_TOKENS=8192
      - MAX_TOTAL_TOKENS=10240
    ports:
      - 8080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    volumes:
      - /var/ragnarok/TEI/data:/data
    environment:
      - MODEL_ID=WhereIsAI/UAE-Large-V1
      - MAX_CLIENT_BATCH_SIZE=128
      - POOLING=cls
    ports:
      - 8081:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

volumes:
  backups:
    driver: local
  index-data:
    driver: local
